name: Build Qt Application for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        
    - name: Setup MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        
    - name: Build
      run: |
        mkdir build
        cd build
        qmake ../QT4in1.pro CONFIG+=debug
        mingw32-make
        
    - name: Package application
      run: |
        cd build/debug
        windeployqt QT4in1.exe
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/debug/QT4in1.exe