name: Qt Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-on-windows:
    name: Build Qt Application for Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install Qt and MinGW
      run: |
        choco install qt --version=6.7.1 -y  # Install Qt 6.7.1
        choco install mingw -y  # Install MinGW compiler

    - name: Set up Qt environment
      run: |
        # Set environment variables for Qt and MinGW
        $env:QTDIR = "C:\Qt\6.7.1\mingw_64"
        $env:PATH += ";$env:QTDIR\bin"
        $env:PATH += ";C:\ProgramData\chocolatey\bin"
        
        # Navigate to the project directory and run qmake
        cd ${{ github.workspace }}  # Change to the workspace directory
        & "$env:QTDIR\bin\qmake" QT4in1.pro  # Configure your project with the .pro file

    - name: Build Qt Project
      run: |
        mingw32-make  # Build the project using MinGW

    - name: Package Windows .exe file
      run: |
        mkdir output
        copy /Y .\release\QT4in1.exe .\output\QT4in1.exe  # Replace with your .exe file name
      shell: cmd

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: QtAppExecutable
        path: output/QT4in1.exe  # Path to the generated .exe file
