name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Qt Installer
        run: |
          mkdir C:\Qt
          cd C:\Qt
          curl -LO "https://download.qt.io/official_releases/qt/6.7/6.7.1/qt-unified-windows-x64-v6.7.1.exe"

      - name: Install Qt
        run: |
          & C:\Qt\qt-unified-windows-x64-v6.7.1.exe --silent --install=C:\Qt --modules=qtbase,qtdeclarative,qttools,qtwidgets,qtcharts
          del C:\Qt\qt-unified-windows-x64-v6.7.1.exe  # Clean up installer

      - name: Build the application
        run: |
          mkdir build
          cd build
          "C:\Qt\Tools\mingw1120_64\bin\qmake.exe" ../QT4in1.pro
          "C:\Qt\Tools\mingw1120_64\bin\mingw32-make.exe" -f Makefile.Debug -j12
