name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Qt
        run: |
          choco install qt --version=6.7.2 --params="'/InstallDir:C:\Qt'"
         

      - name: Build the application
        run: |
          mkdir build
          cd build
          "C:\Qt\Tools\mingw1120_64\bin\qmake.exe" ../QT4in1.pro
          "C:\Qt\Tools\mingw1120_64\bin\mingw32-make.exe" -f Makefile.Debug -j12

      
