name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-qmake qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
          
      - name: Configure Qt Project
        run: |
          qmake QT4in1.pro
          make

      - name: Run Unit Tests
        run: |
          ./tests/test_executable  # Replace with your test executable

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Releases
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/your_application_binary  # Replace with your binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
