name: Build Qt Application for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Run qmake
      run: |
        qmake
      
    - name: Build
      run: |
        nmake

    - name: Run tests
      run: |
        nmake check

    - name: Package application
      run: |
        windeployqt ./${{ github.event.repository.name }}.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: ./${{ github.event.repository.name }}.exe