name: Qt Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-on-windows:
    name: Build Qt Application for Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Qt 6.7.1 and MinGW
      run: |
        choco install qt --version=6.7.1  # Install Qt 6.7.1
        choco install mingw  # Install MinGW compiler

    - name: Configure Qt Project
      run: |
        & "C:\Qt\6.7.1\mingw_64\bin\qtenv2.bat"  # Set up Qt environment with MinGW
        qmake QT4in1.pro  # Configure your project with the .pro file

    - name: Build Qt Project
      run: |
        & "C:\Qt\6.7.1\mingw_64\bin\qtenv2.bat"  # Set up Qt environment again before building
        mingw64-make  # Build the project using MinGW

    - name: Package Windows .exe file
      run: |
        mkdir output
        copy /Y .\release\QT4in1.exe .\output\QT4in1.exe 
      shell: cmd

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: QtAppExecutable
        path: output/QT4in1.exe  
