name: Build Qt Application for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Install OpenSSL
      run: |
        choco install openssl -y
        echo "OPENSSL_ROOT_DIR=C:\Program Files\OpenSSL-Win64" >> $GITHUB_ENV
        echo "C:\Program Files\OpenSSL-Win64\bin" >> $GITHUB_PATH
        
    - name: Build
      run: |
        mkdir release
        cd release
        qmake ..\QT4in1.pro CONFIG+=debug
        nmake
        
    - name: Package application
      run: |
        cd release\debug
        windeployqt QT4in1.exe
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: release\QT4in1.exe